### ISSUE TITLE
Fails to build on x86 without SSE2 due to outdated quanta dep

### ISSUE THREAD

**Issue by wez** [antifuchs/governor#178] opened 2023-04-08 22:43 UTC
This is the underlying issue:
* https://github.com/metrics-rs/quanta/issues/69

surfaces over in:
* https://github.com/wez/wezterm/issues/3472

Please consider updating to a current version of quanta

**Comment by antifuchs** [comment] 2023-04-09 19:08
Known bug (#174), addressed in #175, which unfortunately is not straightforward: There's a 50% perf regression in our quanta-based benchmarks that I haven't been able to track down yet.

If you want to quickly fix this, pull in governor without default features & leave out the `quanta` feature; that should compile it with `std::time::Instant` as the default clock.

Separately, I'm surprised: is this crate working on x86? I thought due to the use of `AtomicU64` in #89, this crate doesn't work on non-64bit platforms.

**Comment by wez** [comment] 2023-04-09 19:35
Thanks; I already found that I can omit the `quanta` feature.

re: 32-bit systems, I don't know how/if it works. I was passing on a build failure from @kekePower who is packaging wezterm for the Mageia distribution.  Apparently with quanta removed (only the `std` feature enabled) it compiles, so it should work?

**Closed** 2023-05-20 17:34 UTC
